---

- name: Include OS family specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Docker CE
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Set storage driver when required
  include_tasks: config-driver.yml

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true

- name: get docker info
  docker_host_info:
  register: dockerinfo

- name: show it
  debug:
    var: dockerinfo.host_info.Driver
