---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint:
  name: yamllint
platforms:
  - name: docker-debian-10
    image: debian:10
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /tmp/docker-debian-10:/var/lib/docker
  - name: docker-debian-9
    image: debian:9
    command: /lib/systemd/systemd
    privileged: true
    volumes:
      - /tmp/docker-debian-9:/var/lib/docker
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      gather_timeout: 30
      interpreter_python: auto
      jinja2_extensions: jinja2.ext.do
      timeout: 30
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
